Added support for PHP 8 and composer 2
avto-dev/stacked-dumper-laravel pull request #7
Opened 2020-12-17 08:52 UTC by IgorKorytin

## Description

## Unreleased

### Added

- Support PHP `8.x`

### Changed

- Composer `2.x` is supported now

Fixes # (issue)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I wrote unit tests for my code _(if tests is required for my changes)_
- [ ] I have made changes in `CHANGELOG.md` file

2020-12-17 09:39 UTC, IgorKorytin commented on .github/workflows/tests.yml
> +    runs-on:  ubuntu-20.04
```suggestion
    runs-on: ubuntu-20.04
```

2020-12-21 05:37 UTC, tarampampam requested changes

2020-12-21 05:37 UTC, tarampampam commented on Makefile
> +	docker-compose run $(RUN_APP_ARGS) app composer update -n --prefer-dist --no-interaction
```suggestion
	docker-compose run $(RUN_APP_ARGS) app composer update -n --prefer-dist
```

2020-12-21 05:37 UTC, tarampampam commented
:+1: Great thanks for your contribution!

But can you also update:

- [ ] [phpunit.xml](https://github.com/avto-dev/stacked-dumper-laravel/runs/1569407905?check_suite_focus=true#step:11:15) ([example](https://github.com/spiral/roadrunner-laravel/blob/v3.7.0/phpunit.xml.dist))

2020-12-25 14:42 UTC, tarampampam requested changes

2020-12-25 14:42 UTC, tarampampam commented on .github/workflows/tests.yml
> +    runs-on:  ubuntu-20.04
```suggestion
    runs-on: ubuntu-20.04
```

2020-12-25 14:42 UTC, tarampampam commented on CHANGELOG.md
> +## Unreleased
```suggestion
## v1.4.0
```

2020-12-30 09:05 UTC, merged